[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    '@aave/core-v3/=lib/aave-v3-core/',
    '@aave/periphery-v3/=lib/aave-v3-periphery/',
    'aave-helpers/=lib/aave-helpers/src/',
    '@uniswap/v3-core/=lib/v3-core/',
    'solidity-utils/=lib/aave-helpers/lib/solidity-utils/src/'
]
fs_permissions = [
    { access = "read", path = "./out/"},
    { access = "read", path = "./script/input/"},
    { access = "read-write", path = "./script/output/"},
    { access = "write", path = "./reports" }
]
evm_version = 'cancun'
solc_version = '0.8.10'
optimizer = true
optimizer_runs = 100000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
